# Generated by Django 4.2.3 on 2023-08-08 13:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_titulo', models.CharField(max_length=100, verbose_name='Título do Texto')),
                ('index_text', tinymce.models.HTMLField(verbose_name='Texto da página Home/Index')),
                ('index_data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('index_data_ult_altera', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
            ],
            options={
                'verbose_name': 'Index',
                'ordering': ['index_titulo', 'index_data_criado', 'index_data_ult_altera'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_nome', models.CharField(max_length=100, unique=True, verbose_name='Título do Módulo')),
                ('mod_seq', models.IntegerField(default=0, unique=True, verbose_name='Número de sequência do Módulo')),
                ('mod_objetivo_geral', models.CharField(max_length=500, verbose_name='Objetivo Geral do Módulo')),
                ('mod_data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('mod_data_ult_altera', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
            ],
            options={
                'verbose_name': 'Módulo',
                'ordering': ['mod_seq'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rot_nome', models.CharField(max_length=100, unique=True, verbose_name='Título do Roteiro')),
                ('rot_seq', models.IntegerField(verbose_name='Número de sequência do Roteiro')),
                ('rot_objetivo_geral', models.CharField(max_length=500, verbose_name='Objetivo Geral do Roteiro')),
                ('rot_objetivos_espec', tinymce.models.HTMLField(verbose_name='Objetivos Específicos do Roteiro')),
                ('rot_simulador', models.CharField(choices=[('0', 'Sem Simulador'), ('1', 'Sinal'), ('2', 'Amostras'), ('3', 'Quantizador Genérico'), ('4', 'Quantizador Uniforme')], default='1', max_length=1, verbose_name='Simulador do Roteiro')),
                ('rot_subsidio', tinymce.models.HTMLField(verbose_name='Subsídios do Roteiro')),
                ('rot_biblio', tinymce.models.HTMLField(verbose_name='Bibliografia do Roteiro')),
                ('rot_exercicios', tinymce.models.HTMLField(verbose_name='Exercícios do Roteiro')),
                ('rot_data_criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('rot_data_ult_altera', models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração')),
                ('rot_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'ordering': ['rot_modulo', 'rot_seq'],
                'unique_together': {('rot_modulo', 'rot_seq')},
            },
        ),
    ]
