# Generated by Django 4.2.3 on 2023-08-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.AlterUniqueTogether(
            name='roteiro',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='rot_modulo',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
        migrations.DeleteModel(
            name='Roteiro',
        ),
    ]
